includes:
  - base.yaml
model:
<<<<<<< HEAD
  model_name: CIGAGIN
ood:
  ood_alg: CIGA
  ood_param: 0.8
  extra_param:
    - 4
    - 2
train:
  max_epoch: 100
  lr: 0.001
log_file: default
=======
  model_name: CIGAvGIN
ood:
  ood_alg: CIGA
  ood_param: 0.8    # causal ratio
  extra_param:
    - 1 #1e-4
train:
  max_epoch: 200
  lr: 1e-3
>>>>>>> 5c04bf7a724687acfda7ac6e1b54b80646b4605c
