exp_round:
  - 1
  - 5
  - 10
lr:
  # - 1e-2
  - 1e-3
  # - 1e-4
ood_param:
  - 0.5
  - 1
  - 2
  - 4
extra_param:
  -     # learn_edge_att
    - true
  -      # decay_interval
    - 10
    - 20
    # - 30
    - 40
  -      # final_r
    # - 0.3
    - 0.5
    - 0.7
    - 0.8
