includes:
  - base.yaml
model:
  model_name: CIGAGIN
ood:
  ood_alg: CIGA
  ood_param: 0.3    # causal ratio
  extra_param:
    - 2    # alpha for contrastive loss
train:
  max_epoch: 100
  lr: 1e-3
  mile_stones: [150]


