includes:
  - base.yaml
model:
  model_name: DIRvGIN
ood:
  ood_alg: DIR
<<<<<<< HEAD
  ood_param: 0.8     # causal ratio
  extra_param:
    - 1e-4     # additional loss control
train:
  max_epoch: 200
  train_bs: 32
  lr: 1e-3


=======
  ood_param: 0.25
  extra_param:
    - 0.01
train:
  max_epoch: 200
  train_bs: 32
  lr: 0.001
  weight_decay: 0.0
log_file: lb_sweeping
num_workers: 0
>>>>>>> 5c04bf7a724687acfda7ac6e1b54b80646b4605c
