includes:
  - base.yaml
model:
  model_name: DIRvGIN
ood:
  ood_alg: DIR
  ood_param: 0.6    # causal ratio
  extra_param:
    - 1e-4
train:
<<<<<<< HEAD
  max_epoch: 100
=======
  max_epoch: 200
>>>>>>> 5c04bf7a724687acfda7ac6e1b54b80646b4605c
  lr: 1e-3
  mile_stones: [300]

