includes:
  - base.yaml
model:
  model_name: CIGAvGIN
ood:
  ood_alg: CIGA
  ood_param: 0.6
  extra_param:
    - 0.5
    - 0.5
train:
  max_epoch: 200
  lr: 0.001
  mile_stones:
    - 300
log_file: default
