includes:
  - base.yaml
model:
<<<<<<< HEAD
  model_name: CIGAGIN
ood:
  ood_alg: CIGA
  ood_param: 0.6
  extra_param:
    - 1
    - 0
train:
  max_epoch: 100
  lr: 0.001
  mile_stones:
    - 300
  train_bs: 128
  val_bs: 128
  test_bs: 128
log_file: default
=======
  model_name: CIGAvGIN
ood:
  ood_alg: CIGA
  ood_param: 0.6    # causal ratio
  extra_param:
    - 1
train:
  max_epoch: 200
  lr: 1e-3
  mile_stones: [300]

>>>>>>> 5c04bf7a724687acfda7ac6e1b54b80646b4605c
