includes:
  - base.yaml
model:
  model_name: DIRvGIN
ood:
  ood_alg: DIR
<<<<<<< HEAD
  ood_param: 0.6    # causal ratio
  extra_param:
    - 1e-4
train:
  max_epoch: 200
  lr: 1e-3
  mile_stones: [300]

=======
  ood_param: 0.7
  extra_param:
    - 10.0
train:
  max_epoch: 200
  lr: 0.001
  mile_stones:
    - 300
  weight_decay: 0.0
log_file: lb_sweeping
num_workers: 0
>>>>>>> 5c04bf7a724687acfda7ac6e1b54b80646b4605c
