includes:
  - base.yaml
model:
  model_name: CIGAGIN
ood:
  ood_alg: CIGA
<<<<<<< HEAD
  ood_param: 0.3
  extra_param:
    - 0.5
    - 1
train:
  lr: 0.001
  mile_stones:
    - 150
log_file: default
=======
  ood_param: 0.25    # causal ratio
  extra_param:
    - 2     # additional loss control
train:
  max_epoch: 200
  lr: 1e-3
  mile_stones: [150]


>>>>>>> 5c04bf7a724687acfda7ac6e1b54b80646b4605c
